project_id = "gwjsivqksyimuabbdyqq"

[functions.cozycraft-assistant]
verify_jwt = false

[functions.create-paymongo-checkout]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false

[functions.cancel-paymongo-checkout]
verify_jwt = false

[functions.sync-paymongo-payments]
verify_jwt = false
