export const catalogTaxonomy: Record<string, string[]> = {
  "Living room": [
    "2-Seater Fabric Sofa",
    "3-Seater Fabric Sofa",
    "Sectional Sofa",
    "Recliner Sofa",
    "Sofa Bed",
    "Wooden Coffee Table",
    "Glass Coffee Table",
    "Round Coffee Table",
    "Storage Coffee Table",
    "Marble Coffee Table",
    "Wooden TV Stand",
    "Floating TV Stand",
    "Corner TV Stand",
    "TV Cart",
    "Modern TV Stand",
  ],
  Bedroom: [
    "Single Size Bed",
    "Double Size Bed",
    "Queen Size Bed",
    "King Size Bed",
    "Bunk Bed",
    "2-Door Wardrobe",
    "3-Door Wardrobe",
    "Sliding Door Wardrobe",
    "Walk-in Wardrobe",
    "Corner Wardrobe",
    "Wooden Nightstand",
    "Modern Nightstand",
    "Floating Nightstand",
    "Nightstand with Drawer",
    "Metal Nightstand",
  ],
  "Dining room": [
    "Extendable Dining Table",
    "Marble Top Dining Table",
    "Glass Dining Table",
    "Wooden Ornate Dining Table",
    "Metal Industrial Dining Table",
    "Wooden Ornate Dining Chairs",
    "Modern Plastic Dining Chairs",
    "Metal Industrial Dining Chairs",
    "Molded Resin Dining Chairs",
    "Luxury Velvet Dining Chairs",
    "Dining Hutch Cabinet",
    "Buffet Cabinet",
    "Pantry Cabinets",
    "Wine Storage Cabinet",
    "Serving Trolleys",
  ],
};
export const FURNITURE_SUBTYPES = Object.values(catalogTaxonomy).flat();
