type VoucherEmail = { discount_amount: number; points_cost: number; minimum_order_amount: number; expires_at: string };
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function buildVoucherEmail(voucher: VoucherEmail) {
  const money = (n: number) => `₱${Number(n).toLocaleString('en-PH', {maximumFractionDigits:2})}`;
  const expiry = new Intl.DateTimeFormat('en-PH', {timeZone:'Asia/Manila',dateStyle:'long',timeStyle:'short'}).format(new Date(voucher.expires_at));
  const amount = money(voucher.discount_amount);
  const minimum = voucher.minimum_order_amount > 0 ? `Valid on merchandise orders from ${money(voucher.minimum_order_amount)}.` : 'No minimum merchandise spend.';
  const subject = `Your ${amount} CozyCraft voucher is ready`;
  const text = `Your Home Circle voucher is ready. You exchanged ${voucher.points_cost} points for ${amount} off. ${minimum} Expires ${expiry} (Philippine time). Select your voucher at checkout before placing your order. One voucher per order; the applied discount is shown at checkout. View your wallet: https://www.cozycraftfurnitures.com/profile?tab=home-circle`;
  const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f3f0e9;color:#292d26;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:auto;background:#fff;border:1px solid #e4dfd4;border-radius:22px;overflow:hidden"><tr><td align="center" style="padding:30px 24px;border-bottom:1px solid #e8e2d7"><img src="https://www.cozycraftfurnitures.com/email-logo.png" width="150" alt="CozyCraft Furnitures" style="display:block;width:150px;max-width:100%;height:auto"><p style="font-size:10px;letter-spacing:3px;color:#777565;margin:20px 0 0">HOME CIRCLE</p></td></tr><tr><td style="padding:32px 24px"><h1 style="font-family:Georgia,serif;font-size:34px;font-weight:400;line-height:1.15;margin:0 0 18px">A little thank-you,<br>for your home.</h1><p style="font-size:14px;line-height:1.8;color:#706e64">Your points have become something lovely. Your new voucher is saved to your Home Circle wallet and ready for your next order.</p><table role="presentation" width="100%" style="margin:24px 0;background:#2e352b;border-radius:16px;color:#f6f2e8"><tr><td style="padding:26px"><p style="font-size:10px;letter-spacing:2px;margin:0 0 12px;color:#ccd4c3">YOUR CLAIMED VOUCHER</p><p style="font-family:Georgia,serif;font-size:44px;margin:0">${escape(amount)} off</p><p style="font-size:13px;margin:14px 0 0">${voucher.points_cost} points exchanged</p><p style="font-size:12px;line-height:1.8;color:#d7dccf;margin:18px 0 0">${escape(minimum)}<br>Expires ${escape(expiry)}<br>Philippine time (Asia/Manila)</p></td></tr></table><p style="font-size:14px;line-height:1.8;color:#706e64">Choose this voucher in the Home Circle section at checkout. Review the discount, then place your order as usual.</p><p style="margin:26px 0"><a href="https://www.cozycraftfurnitures.com/profile?tab=home-circle" style="display:inline-block;background:#292d26;color:white;padding:15px 24px;border-radius:10px;font-size:13px;font-weight:bold;text-decoration:none">View my vouchers →</a></p><p style="font-size:11px;color:#817c70;line-height:1.8">One voucher per order. Voucher eligibility and the final discount are checked securely at checkout. Your wallet stays in sync across the website and app.</p></td></tr><tr><td style="padding:20px 24px;background:#eeeae0;color:#777166;font-size:11px;line-height:1.7">CozyCraft Furnitures · Furniture for a life well lived.<br>This email confirms a voucher claim on your account. No action is needed if you are saving it for later.</td></tr></table></td></tr></table></body></html>`;
  return {subject,text,html};
}
