-- Storefront experience controls with deliberately narrow reads and writes.
-- Product comparison and fit checking stay client-side; only durable customer
-- intent and administrator-managed configuration live in Postgres.

create table public.delivery_service_areas (
  id bigint generated by default as identity primary key,
  area_code text not null,
  name text not null,
  description text not null default '',
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  free_delivery_minimum numeric(12,2) check (free_delivery_minimum is null or free_delivery_minimum >= 0),
  lead_time_min_days integer not null default 2 check (lead_time_min_days between 0 and 60),
  lead_time_max_days integer not null default 5 check (lead_time_max_days between lead_time_min_days and 90),
  assembly_available boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index delivery_service_areas_area_code_unique
  on public.delivery_service_areas (lower(area_code));
create index delivery_service_areas_public_lookup_idx
  on public.delivery_service_areas (active, sort_order, id)
  include (area_code, name, delivery_fee, free_delivery_minimum, lead_time_min_days, lead_time_max_days, assembly_available);

create table public.product_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  alert_type text not null check (alert_type in ('back_in_stock', 'price_drop')),
  target_price numeric(12,2) check (target_price is null or target_price >= 0),
  active boolean not null default true,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id, alert_type)
);

create index product_alerts_active_product_idx
  on public.product_alerts (product_id, alert_type)
  include (user_id, target_price, created_at)
  where active;
create index product_alerts_user_idx
  on public.product_alerts (user_id, active, created_at desc);

create table public.search_synonyms (
  id bigint generated by default as identity primary key,
  term text not null,
  synonyms text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(trim(term)) between 2 and 80),
  check (cardinality(synonyms) <= 20)
);

create unique index search_synonyms_term_unique
  on public.search_synonyms (lower(term));
create index search_synonyms_public_lookup_idx
  on public.search_synonyms (active, lower(term)) include (synonyms);

create table public.search_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  normalized_query text not null,
  result_count integer not null check (result_count >= 0),
  collection text,
  created_at timestamptz not null default now(),
  check (char_length(query) between 2 and 120),
  check (char_length(normalized_query) between 2 and 120)
);

create index search_events_admin_recent_idx
  on public.search_events (created_at desc)
  include (normalized_query, result_count, collection);
create index search_events_user_dedupe_idx
  on public.search_events (user_id, normalized_query, created_at desc);

alter table public.delivery_service_areas enable row level security;
alter table public.product_alerts enable row level security;
alter table public.search_synonyms enable row level security;
alter table public.search_events enable row level security;

create policy delivery_service_areas_public_read
  on public.delivery_service_areas for select
  to anon, authenticated
  using (active or (select private.is_staff()));
create policy delivery_service_areas_staff_insert
  on public.delivery_service_areas for insert
  to authenticated with check ((select private.is_staff()));
create policy delivery_service_areas_staff_update
  on public.delivery_service_areas for update
  to authenticated
  using ((select private.is_staff()))
  with check ((select private.is_staff()));
create policy delivery_service_areas_staff_delete
  on public.delivery_service_areas for delete
  to authenticated using ((select private.is_staff()));

create policy product_alerts_owner_read
  on public.product_alerts for select
  to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));
create policy product_alerts_owner_insert
  on public.product_alerts for insert
  to authenticated with check ((select auth.uid()) = user_id);
create policy product_alerts_owner_update
  on public.product_alerts for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy product_alerts_owner_delete
  on public.product_alerts for delete
  to authenticated using ((select auth.uid()) = user_id);

create policy search_synonyms_public_read
  on public.search_synonyms for select
  to anon, authenticated
  using (active or (select private.is_staff()));
create policy search_synonyms_staff_insert
  on public.search_synonyms for insert
  to authenticated with check ((select private.is_staff()));
create policy search_synonyms_staff_update
  on public.search_synonyms for update
  to authenticated
  using ((select private.is_staff()))
  with check ((select private.is_staff()));
create policy search_synonyms_staff_delete
  on public.search_synonyms for delete
  to authenticated using ((select private.is_staff()));

create policy search_events_staff_read
  on public.search_events for select
  to authenticated using ((select private.is_staff()));

revoke all on table public.delivery_service_areas from anon, authenticated;
revoke all on table public.product_alerts from anon, authenticated;
revoke all on table public.search_synonyms from anon, authenticated;
revoke all on table public.search_events from anon, authenticated;
grant select on table public.delivery_service_areas to anon, authenticated;
grant insert, update, delete on table public.delivery_service_areas to authenticated;
grant select, insert, update, delete on table public.product_alerts to authenticated;
grant select on table public.search_synonyms to anon, authenticated;
grant insert, update, delete on table public.search_synonyms to authenticated;
grant select on table public.search_events to authenticated;
grant usage, select on sequence public.delivery_service_areas_id_seq to authenticated;
grant usage, select on sequence public.search_synonyms_id_seq to authenticated;

create or replace function public.record_catalog_search(
  p_query text,
  p_result_count integer,
  p_collection text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_query text := left(trim(coalesce(p_query, '')), 120);
  v_normalized text;
begin
  if v_user_id is null or char_length(v_query) < 2 then
    return;
  end if;
  v_normalized := lower(regexp_replace(v_query, '\s+', ' ', 'g'));
  if exists (
    select 1
    from public.search_events
    where user_id = v_user_id
      and normalized_query = v_normalized
      and created_at > now() - interval '15 minutes'
  ) then
    return;
  end if;
  insert into public.search_events (user_id, query, normalized_query, result_count, collection)
  values (v_user_id, v_query, v_normalized, greatest(coalesce(p_result_count, 0), 0), left(nullif(trim(p_collection), ''), 80));
end;
$$;

revoke all on function public.record_catalog_search(text, integer, text) from public, anon;
grant execute on function public.record_catalog_search(text, integer, text) to authenticated;

insert into public.delivery_service_areas
  (area_code, name, description, delivery_fee, free_delivery_minimum, lead_time_min_days, lead_time_max_days, assembly_available, sort_order)
values
  ('metro-manila', 'Metro Manila', 'NCR cities and municipalities', 650, 50000, 2, 4, true, 10),
  ('greater-manila', 'Greater Manila Area', 'Nearby areas in Bulacan, Cavite, Laguna, and Rizal', 950, 75000, 3, 6, true, 20),
  ('luzon', 'Other Luzon areas', 'Provincial delivery across Luzon', 1450, 100000, 5, 9, false, 30),
  ('visayas', 'Visayas', 'Inter-island furniture delivery', 2250, 150000, 8, 14, false, 40),
  ('mindanao', 'Mindanao', 'Inter-island furniture delivery', 2450, 150000, 9, 16, false, 50);

insert into public.search_synonyms (term, synonyms)
values
  ('sofa', array['couch', 'settee', 'sectional']),
  ('cabinet', array['storage', 'cupboard', 'credenza', 'console']),
  ('nightstand', array['bedside table', 'bedside cabinet']),
  ('dining chair', array['dining seat', 'accent chair']),
  ('tv stand', array['media console', 'entertainment unit']);
