-- Newsletter addresses are personal data. Store them behind a public Edge
-- Function and do not expose the table itself through the Data API.
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'active'
    check (status in ('active', 'unsubscribed')),
  source text not null default 'homepage',
  consented_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint newsletter_subscribers_email_normalized
    check (email = lower(btrim(email)) and char_length(email) between 3 and 254),
  constraint newsletter_subscribers_email_unique unique (email)
);
comment on table public.newsletter_subscribers is
  'Consent records for CozyCraft product and editorial email updates.';
comment on column public.newsletter_subscribers.consented_at is
  'Timestamp when the visitor explicitly submitted the newsletter form.';
create index if not exists newsletter_subscribers_active_created_idx
  on public.newsletter_subscribers (created_at desc)
  where status = 'active';
alter table public.newsletter_subscribers enable row level security;
-- RLS is deliberately left without client policies. The service-role client
-- inside newsletter-subscribe is the only application path to this table.
revoke all on table public.newsletter_subscribers from anon, authenticated;
revoke all on sequence public.newsletter_subscribers_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.newsletter_subscribers to service_role;
grant usage, select on sequence public.newsletter_subscribers_id_seq to service_role;
